name: Build ffmpeg for macOS

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: macos-13 
    steps:
    - name: Install dependencies
      run: |
        brew install cargo-c nasm
        # webp formula doesn't link statically, the other formulas depend on it
        brew uninstall webp aom composer gd jpeg-xl libavif php
    
    - name: Build and install pkg-config
      run: |
        wget -q https://pkgconfig.freedesktop.org/releases/pkg-config-0.29.2.tar.gz
        tar xf pkg-config-0.29.2.tar.gz
        cd pkg-config-0.29.2
        ./configure --with-internal-glib
        make -j $(sysctl -n hw.logicalcpu)
        make install
    
    - name: Build and install webp
      run: | 
        wget -q https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-1.2.2.tar.gz
        tar xf libwebp-1.2.2.tar.gz
        cd libwebp-1.2.2
        ./configure --disable-dependency-tracking --disable-shared --enable-static --disable-gif --disable-gl --enable-libwebpdecoder --enable-libwebpdemux --enable-libwebpmux
        make -j $(sysctl -n hw.logicalcpu)
        make install
    
    - name: Restore rav1e cache
      id: cache-restore
      uses: actions/cache/restore@v3
      with:
        key: macos-rav1e-0.6.6
        path: |
          /usr/local/lib/**/*rav1e*
          /usr/local/bin/**/*rav1e*
          /usr/local/include/**/*rav1e*

    - name: Build and install rav1e
      if: ${{ steps.cache-restore.outputs.cache-hit != 'true' }}
      run: |
        wget -q https://github.com/xiph/rav1e/archive/v0.6.6.tar.gz
        tar xf v0.6.6.tar.gz
        cd rav1e-0.6.6
        cargo cinstall --library-type=staticlib --crt-static --release
    
    - name: Save rav1e cache
      if: ${{ steps.cache-restore.outputs.cache-hit != 'true' }}
      uses: actions/cache/save@v3
      with:
        key: macos-rav1e-0.6.6
        path: |
          /usr/local/lib/**/*rav1e*
          /usr/local/bin/**/*rav1e*
          /usr/local/include/**/*rav1e*
    
    - name: Setup ffmpeg
      run: |
        wget -q https://ffmpeg.org/releases/ffmpeg-6.0.tar.bz2
        echo "47d062731c9f66a78380e35a19aac77cebceccd1c7cc309b9c82343ffc430c3d  ffmpeg-6.0.tar.bz2" | shasum -a 256 -c -
        tar xf ffmpeg-6.0.tar.bz2
        cd ffmpeg-6.0
        ./configure --pkg-config-flags=--static --enable-static --enable-small --enable-zlib --enable-libwebp --enable-librav1e --disable-autodetect --disable-debug --disable-shared --disable-ffplay --disable-ffprobe --disable-everything --disable-network --disable-debug --disable-doc --disable-iconv --disable-bzlib --disable-libxcb-shm --disable-libxcb --disable-lzma --enable-protocol=file --enable-filter=scale --enable-demuxer=image2 --enable-demuxer=mov --enable-encoder=mjpeg --enable-decoder=mjpeg --enable-demuxer=mjpeg --enable-muxer=mjpeg --enable-encoder=librav1e --enable-decoder=av1 --enable-decoder=av1 --enable-demuxer=av1 --enable-muxer=avif --enable-encoder=libwebp --enable-encoder=libwebp_anim --enable-decoder=webp --enable-muxer=webp --enable-encoder=png --enable-decoder=png --enable-encoder=apng --enable-decoder=apng --enable-demuxer=apng --enable-muxer=apng --enable-encoder=gif --enable-decoder=gif --enable-demuxer=gif
    
    - name: Build ffmpeg
      run: cd ffmpeg-6.0 && make -j $(sysctl -n hw.logicalcpu)

    - name: Show that it's statically linked
      run: otool -L ffmpeg-6.0/ffmpeg || true
    
    - name: Show used build configuration
      run: ffmpeg-6.0/ffmpeg -hide_banner -buildconf
    
    - name: Show available codecs
      run: ffmpeg-6.0/ffmpeg -hide_banner -codecs
    
    - name: Show available formats
      run: ffmpeg-6.0/ffmpeg -hide_banner -formats
    
    - name: Upload config.log
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: macos-config-log
        path: ffmpeg-6.0/ffbuild/config.log
    
    - name: Upload ffmpeg
      uses: actions/upload-artifact@v3
      with:
        name: macos-x86_64
        path: ffmpeg-6.0/ffmpeg